substitutions:
  devicename: m5stack-atom-lite-shed2
  devicename_upper: M5Stack-Atom-Lite-Shed2

esphome:
  name: $devicename

esp32:
  board: m5stack-atom
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password
  encryption:
    key: !secret api_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

#   Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$devicename"
    password: !secret ap_password

captive_portal:

web_server:
  port: 80

bluetooth_proxy:
  active: true

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a

sensor:
  - platform: aht10
    temperature:
      name: "$devicename Temperature"
    humidity:
      name: "$devicename Humidity"
    update_interval: 60s
  - platform: uptime
    name: "$devicename Uptime Sensor"
    id: uptime_sensor
    update_interval: 60s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? to_string(days) + "d " : "") +
                (hours ? to_string(hours) + "h " : "") +
                (minutes ? to_string(minutes) + "m " : "") +
                (to_string(seconds) + "s")
              ).c_str();
  - platform: wifi_signal
    name: "$devicename WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "$devicename Uptime"

button:
  - platform: restart
    name: "$devicename Restart"
  - platform: safe_mode
    name: "$devicename Restart (Safe Mode)"
  - platform: factory_reset
    name: "$devicename Factory Reset"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "$devicename IP Address"
      id: ipaddress
    ssid:
      name: "$devicename SSID"
      id: ssid
    bssid:
      name: "$devicename BSSID"
    mac_address:
      name: "$devicename Mac Address"
  - platform: template
    name: "$devicename Uptime Human Readable"
    id: uptime_human
    icon: mdi:clock-start
