alias: Scene Example
description: "Example automation that creates a dynamic scene to snapshot an entity or group of entities before applying a pre-defined scene when motion is detected. When the motion stops the dynamic scene is applied and then deleted."
trigger:
  - platform: state
    entity_id:
      - binary_sensor.landing_motion
    from: "off"
    to: "on"
    id: detected
  - platform: state
    entity_id:
      - binary_sensor.landing_motion
    from: "on"
    to: "off"
    id: cleared
    for:
      hours: 0
      minutes: 3
      seconds: 0
condition:
  - condition: sun
    before: sunrise
    after: sunset
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - detected
        sequence:
          - service: scene.create
            metadata: {}
            data:
              scene_id: before
              snapshot_entities:
                - light.ikea_led2035g10_landing
          - service: scene.turn_on
            metadata: {}
            target:
              entity_id: scene.landing_light
      - conditions:
          - condition: trigger
            id:
              - cleared
        sequence:
          - service: scene.turn_on
            target:
              entity_id: scene.before
            data: {}
          - service: scene.delete
            metadata: {}
            data: {}
            target:
              entity_id: scene.before
mode: single
